### ISSUE TITLE
Unable to launch (Oculus Native)

### ISSUE THREAD

**Issue by Ant248** [KozGit/DOOM3-BFG-RIFT#5]
Hey, itching to try out this mod but i am receiving windows error "DOOM 3: BFG Edition has stopped working" on launch.

Have tried multiple fresh installs with the mod , without the mod but cant get it to load, unless i don't include the scripts where it boots into the 2D version

**Comment by KozGit** [comment]
Hi,

There is a new repository for the mod  - you can download update version for OpenVR here:

https://github.com/KozGit/DOOM-3-BFG-VR/releases

I apologize, but the OpenVR version has been upgraded, but not tested, so expect some issues.  PLEASE try running the mod in a clean install first, before installing the texture pack.  This will make it much easier to sort out any issues. 
 
If you have any issues, ( and i expect some), please open an issue in the new repository and I'll get to work on fixing them, I'm not adding any more features until the bugs are worked out of this.

Thx!
